sudo: false

language: node_js

node_js:
  - 6
  - 7
  - 8
  - 9

cache:
  directories:
    - node_modules

install:
  - npm i

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coveralls
